version: 2.1

jobs:
  cmake_build:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - setup-toolchain
      - run:
          name: Build vSOMEIP
          command: |
            ./do.sh cmake-build

commands:
  setup-toolchain:
    description: |
      Install C++ build and test toolchains CMake, GCC and Gtest
    steps:
      - run:
          name: Install project dependencies
          command: |
            sudo apt update
            sudo apt install -y ninja-build git unzip cmake build-essential libboost-all-dev googletest-tools
            sudo apt update

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - cmake_build