version: 2.1

jobs:
  cmake_build:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - setup-toolchain
      - run:
          name: Run do.sh file to build the shared libraries
          command: |
            mkdir build ; cd build ; cmake .. ; make

commands:
  setup-toolchain:
    description: |
      Install C++ build and test toolchains CMake, GCC and Gtest
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build git unzip cmake g++-12 libstdc++-12-dev

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - cmake_build